### ISSUE TITLE
NPE at XdtDiffWriter: line 409

### ISSUE THREAD

**Issue by bitrott** [CameronWills/FatAntelope#1]
In the case where there is an element that is missing/was removed from the target instance you are passing a "null" to WriteElement at line 230. This causes an NPE at line 409 when it attempts to access the Parent property.

**Comment by CameronWills** [comment]
Thanks for that. I've committed a fix and added some unit tests for removing elements - speaks about my poor test coverage that remove elements wasn't even being tested :(
https://github.com/CameronWills/FatAntelope/releases/tag/0.2.6
