### ISSUE TITLE
Case error in generated XDT

### ISSUE THREAD

**Issue by derekgreer** [CameronWills/FatAntelope#4]
I have a target file with the following 

```
...
</connectionStrings>
  <location path="." inheritInChildApplications="false">
...
```

The generated XDT contains the following:

```
...
<location path="." inheritInChildApplications="false" xdt:Transform="InsertAfter(/configuration/connectionstrings)">
...
```

Upon attempting to apply the XDT, it fails due to the casing of connectionstrings.

**Comment by CameronWills** [comment]
Great thanks for logging the issue. Somehow I've so far managed to miss this scenario as well as general case sensitivity in tests and diffing real world .config files. Anyway, I've pushed a fix in v0.2.9:
https://github.com/CameronWills/FatAntelope/releases/tag/0.2.9

I'll close this issue for now - but feel free to comment and reopen if still experiencing the issue.
